BookingsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: BookingsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: status
        AttributeType: S
      - AttributeName: bookingTime
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: statusAndBookingTimeIndex
        KeySchema:
          - AttributeName: status
            KeyType: HASH
          - AttributeName: bookingTime
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
            